import { Facilioicons } from './build/Facilioicons.model.ts';
export declare type FacilioiconsNameSubset<T extends Readonly<Facilioicons[]>> = T[number]['name'];
export * from './build/Facilioicons-Air Handling Unit.icon';
export * from './build/Facilioicons-Announcement.icon';
export * from './build/Facilioicons-Apps.icon';
export * from './build/Facilioicons-Areasqft.icon';
export * from './build/Facilioicons-Auto size.icon';
export * from './build/Facilioicons-Billing.icon';
export * from './build/Facilioicons-Booking.icon';
export * from './build/Facilioicons-Catalogue.icon';
export * from './build/Facilioicons-CCTV.icon';
export * from './build/Facilioicons-Checked.icon';
export * from './build/Facilioicons-close.icon';
export * from './build/Facilioicons-Community.icon';
export * from './build/Facilioicons-conditional format.icon';
export * from './build/Facilioicons-Contracts.icon';
export * from './build/Facilioicons-CSV.icon';
export * from './build/Facilioicons-Dashboard.icon';
export * from './build/Facilioicons-Default .icon';
export * from './build/Facilioicons-Default mobile icon.icon';
export * from './build/Facilioicons-Delivery module.icon';
export * from './build/Facilioicons-Desk.icon';
export * from './build/Facilioicons-DOC.icon';
export * from './build/Facilioicons-Documents.icon';
export * from './build/Facilioicons-facilities.icon';
export * from './build/Facilioicons-Fan coil unit.icon';
export * from './build/Facilioicons-File.icon';
export * from './build/Facilioicons-filter 1.icon';
export * from './build/Facilioicons-Floor_map.icon';
export * from './build/Facilioicons-Floors.icon';
export * from './build/Facilioicons-Food area.icon';
export * from './build/Facilioicons-hidden field.icon';
export * from './build/Facilioicons-Home.icon';
export * from './build/Facilioicons-HTML.icon';
export * from './build/Facilioicons-Image.icon';
export * from './build/Facilioicons-Individually track.icon';
export * from './build/Facilioicons-Induction Temp.icon';
export * from './build/Facilioicons-Induction.icon';
export * from './build/Facilioicons-Inspection module.icon';
export * from './build/Facilioicons-Inspection.icon';
export * from './build/Facilioicons-Jobs.icon';
export * from './build/Facilioicons-Legends.icon';
export * from './build/Facilioicons-Lift.icon';
export * from './build/Facilioicons-Location.icon';
export * from './build/Facilioicons-Max Occupancy.icon';
export * from './build/Facilioicons-Notification.icon';
export * from './build/Facilioicons-Occupant.icon';
export * from './build/Facilioicons-Overview.icon';
export * from './build/Facilioicons-Parking.icon';
export * from './build/Facilioicons-PDF.icon';
export * from './build/Facilioicons-pin.icon';
export * from './build/Facilioicons-Privacy policy.icon';
export * from './build/Facilioicons-Profile.icon';
export * from './build/Facilioicons-Retail.icon';
export * from './build/Facilioicons-row heightlong.icon';
export * from './build/Facilioicons-row heightmedium.icon';
export * from './build/Facilioicons-row heightshort.icon';
export * from './build/Facilioicons-search.icon';
export * from './build/Facilioicons-Signature .icon';
export * from './build/Facilioicons-Site swtich.icon';
export * from './build/Facilioicons-sort.icon';
export * from './build/Facilioicons-Storage.icon';
export * from './build/Facilioicons-Summary .icon';
export * from './build/Facilioicons-Tenant.icon';
export * from './build/Facilioicons-Termsandconditions.icon';
export * from './build/Facilioicons-themes.icon';
export * from './build/Facilioicons-Trigger.icon';
export * from './build/Facilioicons-Txt wrap.icon';
export * from './build/Facilioicons-Unchecked.icon';
export * from './build/Facilioicons-Unsupported format.icon';
export * from './build/Facilioicons-URL.icon';
export * from './build/Facilioicons-Variable air volume.icon';
export * from './build/Facilioicons-Vendor.icon';
export * from './build/Facilioicons-Vendors.icon';
export * from './build/Facilioicons-Visits copy 2.icon';
export * from './build/Facilioicons-Visits copy.icon';
export * from './build/Facilioicons-Work order.icon';
export * from './build/Facilioicons-Work permit.icon';
export * from './build/Facilioicons-XLS.icon';
export * from './build/completeIconSet';
export * from './build/Facilioicons.model.ts';
